# Generated by Django 3.1.7 on 2021-02-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=5000, verbose_name='Fotoğraf Linki')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='Yazı')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
